---
name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'The release version, if not set it computes the version automatically'
        required: false
      skip-tests:
        description: 'Whether to skip the tests before pushing the tag'
        required: false
        default: true
      branch:
        description: 'The branch from which the release is cut'
        required: false
        default: 'main'
      dry-run:
        description: 'Skip Git push'
        required: false
        default: true

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.inputs.branch }}
          token: ${{ secrets.RELEASE_TOKEN }}
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
          overwrite-settings: false
      - name: Prepare release branch
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          RELEASE_VERSION: ${{ github.event.inputs.release-version }}
          SKIP_TESTS: ${{ github.event.inputs.skip-tests }}
          DRY_RUN: ${{ github.event.inputs.dry-run }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: .build/cut-release.sh
